using UnityEngine;

public class Teste : MonoBehaviour {
	// Start is called once before the first execution of Update after the MonoBehaviour is created
	void Start() {

	}

	// Update is called once per frame
	void Update() {
		if (Input.GetKey(KeyCode.W)) {
			transform.position += Vector3.back * Time.deltaTime * 10;
		}

		if (Input.GetKey(KeyCode.S)) {
			transform.position += Vector3.forward * Time.deltaTime * 10;
		}

		if (Input.GetKey(KeyCode.A)) {
			transform.position += Vector3.right * Time.deltaTime * 10;
		}

		if (Input.GetKey(KeyCode.D)) {
			transform.position += Vector3.left * Time.deltaTime * 10;
		}
	}
}
